In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
one_dim = np.array([1, 2, 3])
one_dim

array([1, 2, 3])

In [7]:
two_dim = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

two_dim, two_dim.shape

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 (3, 4))

In [8]:
three_dim = np.array([[[1, 2, 3],
                       [4, 5, 6]],
                       
                       [[10, 11, 12],
                       [13, 14, 15]]])
three_dim

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 11, 12],
        [13, 14, 15]]])

In [9]:
three_dim.shape

(2, 2, 3)

In [11]:
one_dim.size, two_dim.size, three_dim.size

(3, 12, 12)

In [12]:
one_dim.ndim, two_dim.ndim, three_dim.ndim

(1, 2, 3)

In [13]:
type(one_dim), type(two_dim), type(three_dim)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
one_dim.dtype, two_dim.dtype, three_dim.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [17]:
df = pd.DataFrame(one_dim)
df

0
0  1
1  2
2  3

In [21]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [24]:
ranged_array = np.arange(0, 100, 3)
ranged_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [25]:
random_1 = np.random.randint(0, 10, size=(7, 2))
random_1

array([[3, 4],
       [5, 8],
       [8, 6],
       [2, 7],
       [2, 2],
       [5, 6],
       [7, 8]])

In [28]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_3 = np.random.rand(3, 5)
random_3

array([[0.4127743 , 0.48242221, 0.72502252, 0.0187898 , 0.95579756],
       [0.97915252, 0.85802444, 0.21535662, 0.87815085, 0.63786311],
       [0.79790855, 0.59349276, 0.80229444, 0.3380978 , 0.45286825]])

In [29]:
np.random.seed(42)
random_4 = np.random.randint(0, 10, size=(4,6))
random_4

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [30]:
random = np.random.randint(1, 10, size=(3, 7))
np.unique(random)

array([1, 2, 3, 4, 5, 7, 9])

In [32]:
random

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [33]:
random[0]

array([9, 1, 3, 7, 4, 9, 3])

In [34]:
#get the first two rows
random[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [35]:
#get the first two values of first two rows
random[:2, :2]

array([[9, 1],
       [5, 3]])

In [39]:
dog = np.random.randint(0, 10, size=(3,5))
cat = np.ones((3,5))


In [40]:
dog, cat

(array([[9, 1, 9, 3, 7],
        [6, 8, 7, 4, 1],
        [4, 7, 9, 8, 8]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [41]:
dog + cat

array([[10.,  2., 10.,  4.,  8.],
       [ 7.,  9.,  8.,  5.,  2.],
       [ 5.,  8., 10.,  9.,  9.]])

In [42]:
mouse = np.random.randint(0, 10, size=(5,3))
mouse

array([[0, 8, 6],
       [8, 7, 0],
       [7, 7, 2],
       [0, 7, 2],
       [2, 0, 4]])

In [43]:
mouse + cat

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

In [44]:
# Tranpose one of the array
mouse.T + cat

array([[1., 9., 8., 1., 3.],
       [9., 8., 8., 8., 1.],
       [7., 1., 3., 3., 5.]])

In [45]:
another_array = np.ones((3,5))

In [46]:
another_array - (mouse.T + cat)

array([[ 0., -8., -7.,  0., -2.],
       [-8., -7., -7., -7.,  0.],
       [-6.,  0., -2., -2., -4.]])

In [47]:
(another_array - (mouse.T + cat)) * cat

array([[ 0., -8., -7.,  0., -2.],
       [-8., -7., -7., -7.,  0.],
       [-6.,  0., -2., -2., -4.]])

In [48]:
twnf = (another_array - (mouse.T + cat)) * cat

In [49]:
twnf ** 2

array([[ 0., 64., 49.,  0.,  4.],
       [64., 49., 49., 49.,  0.],
       [36.,  0.,  4.,  4., 16.]])

In [50]:
np.square(twnf)

array([[ 0., 64., 49.,  0.,  4.],
       [64., 49., 49., 49.,  0.],
       [36.,  0.,  4.,  4., 16.]])

In [51]:
np.mean(twnf)

-4.0

In [52]:
np.max(twnf)

0.0

In [53]:
np.min(twnf)

-8.0

In [54]:
np.std(twnf)

3.141125063837266

In [55]:
np.var(twnf)

9.866666666666667

In [56]:
twnf.reshape(3, 5, 1)

array([[[ 0.],
        [-8.],
        [-7.],
        [ 0.],
        [-2.]],

       [[-8.],
        [-7.],
        [-7.],
        [-7.],
        [ 0.]],

       [[-6.],
        [ 0.],
        [-2.],
        [-2.],
        [-4.]]])

In [58]:
twnf.reshape(3,5,1).T


array([[[ 0., -8., -6.],
        [-8., -7.,  0.],
        [-7., -7., -2.],
        [ 0., -7., -2.],
        [-2.,  0., -4.]]])

In [59]:
int_1 = np.random.randint(0, 10, size=(3, 3))
int_2 = np.random.randint(0, 10, size=(3, 2))

In [60]:
np.dot(int_1, int_2)

array([[114, 141],
       [106, 128],
       [ 49,  46]])

In [61]:
int_3 = np.random.randint(0, 10, size=(4, 3))
int_4 = np.random.randint(0, 10, size=(4, 3))

In [62]:
np.dot(int_3, int_4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [63]:
np.dot(int_3, int_4.T)

array([[ 63,  30,  23,  36],
       [ 58,  18,  34,  36],
       [ 54,  27,  70,  66],
       [124,  60,  90, 102]])

In [64]:
you = np.random.randint(0, 10, size=(2, 4))

i = np.random.randint(0, 10, size=(2, 4))


In [65]:
i > you

array([[ True,  True,  True, False],
       [False, False,  True,  True]])

In [66]:
i > 7

array([[ True, False,  True, False],
       [False, False,  True,  True]])

In [67]:
i == you

array([[False, False, False, False],
       [False, False, False, False]])

In [68]:
np.sort(you)

array([[1, 2, 5, 9],
       [3, 4, 5, 8]])

In [69]:
# Sort the indexes of one of the arrays you just created
np.argsort(you)

array([[2, 0, 1, 3],
       [3, 1, 2, 0]], dtype=int64)

In [70]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(you)

3

In [71]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(you)

2

In [72]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(you, axis=1)

array([3, 0], dtype=int64)

In [73]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(i, axis=0)

array([1, 1, 0, 0], dtype=int64)

In [74]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)

array([[ 0.29612028,  0.26105527,  0.00511346, -0.23458713, -1.41537074],
       [-0.42064532, -0.34271452, -0.80227727, -0.16128571,  0.40405086],
       [ 1.8861859 ,  0.17457781,  0.25755039, -0.07444592, -1.91877122]])

In [75]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])